/**
 * Models for the contents of the Rootlist (folders and playlists)
 * @note this file is generated by AI based on the RootlistApi getContents response
 */
export interface RootFolder {
    type: 'folder';
    addedAt: string; // ISO timestamp
    items: TreeItem[];
    name: string;
    uri: string;
    totalItemCount: number;
}

export type TreeItem = Folder | Playlist;

export interface Folder {
    type: 'folder';
    addedAt: string;
    items: TreeItem[];
    name: string;
    uri: string;
}

export interface Playlist {
    type: 'playlist';
    addedAt: string;
    uri: string;
    name: string;
    description: string;
    images: Image[];
    madeFor: string | null;
    owner: Owner;
    totalLength: number;
    unfilteredTotalLength: number;
    totalLikes: number | null;
    duration: number | null;
    isLoaded: boolean;
    isOwnedBySelf: boolean;
    isPublished: boolean;
    isRootlistable: boolean;
    isSaved: boolean;
    hasEpisodes: boolean | null;
    hasSpotifyTracks: boolean | null;
    hasSpotifyAudiobooks: boolean;
    canAdd: boolean;
    canRemove: boolean;
    canPlay: boolean | null;
    formatListData: FormatListData;
    canReportAnnotationAbuse: boolean;
    hasDateAdded: boolean;
    permissions: any | null;
    collaborators: Collaborators;
    appliedLenses: any[];
    availableSignals: any[];
}

export interface Image {
    url: string;
    label?: string;
}

export interface Owner {
    type: 'user' | string;
    uri: string;
    username?: string;
    displayName?: string;
    images: Image[];
}

export interface FormatListData {
    type: string;
    attributes: Record<string, any>;
}

export interface Collaborators {
    count: number;
    items: CollaboratorItem[];
}

export interface CollaboratorItem {
    // minimal shape; expand if you have examples
    [key: string]: any;
}
